// Annual calendar artwork provides earlier season dates; current listings override future dates.
const AudaxCalendar=(()=>{
 const base='/preview/bespoke/audax-malaysia',official='https://www.audaxmalaysia.com';
 const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
 const earlier=[
 {month:0,dates:'18',name:'Pink Ride 9.0',format:'BRM200',url:official+'/audax-kiarabay-pinkride-9'},
 {month:3,dates:'11–12',name:'Easter Day Team Ride',format:'Flèche 360 km',url:official+'/past-rides'},
 {month:4,dates:'10',name:'LRM1300 training ride',format:'200 km',url:official+'/past-rides'},
 {month:4,dates:'23–27',name:'The Great Loop',format:'LRM1300',url:official+'/past-rides'},
 {month:5,dates:'27–28',name:'Audax Peaks Challenge',format:'BRM300',url:official+'/past-rides'},
 {month:6,dates:'25–26',name:'The Big Hills 8',format:'BRM200 · BRM600',url:official+'/past-rides'},
 {month:7,dates:'15–16',name:'Audax Merdeka Ride',format:'BRM400',url:official+'/past-rides'},
 {month:8,dates:'12–15',name:'Road to Paris',format:'BRM1000',url:official+'/road-to-paris-1000'}
 ];
 const dateMap={'ice-cream-ride':[9,'17–18','20261017','20261019'],'santai-600':[10,'14–15','20261114','20261116'],'final-push':[11,'12–13','20261212','20261214'],'pink-ride':[0,'17','20270117','20270118']};
 let current=[];
 function setRides(rides){current=rides.filter(r=>dateMap[r.id]).map(r=>({month:dateMap[r.id][0],year:r.year,dates:dateMap[r.id][1],name:r.name,format:r.id==='pink-ride'?'Permanent · BRM200':r.distanceLabels.join(' · '),url:base+'/rides/'+r.id+'/',book:r.open?r.id:null,start:dateMap[r.id][2],end:dateMap[r.id][3],venue:r.venue}));current.push({month:10,year:'2026',dates:'1',name:'A Ride with the Super Randonneurs',format:'55 km',url:official+'/superrandonneurs2025',external:true,start:'20261101',end:'20261102',venue:'Antara Daun Cafe, Denai Alam'});current.sort((a,b)=>a.start.localeCompare(b.start));}
 const event=e=>`<li class="season-event"><div class="season-event-date"><time datetime="${e.start?e.start.slice(0,4)+'-'+e.start.slice(4,6)+'-'+e.start.slice(6,8):'2026-'+String(e.month+1).padStart(2,'0')+'-'+e.dates.split('–')[0].padStart(2,'0')}">${e.dates}</time><span>${e.format}</span></div><h4><a href="${e.url}" ${e.url.startsWith(official)?'target="_blank" rel="noopener noreferrer"':''}>${e.name}</a></h4>${e.current?`<div class="season-event-actions">${e.book?`<button type="button" class="season-book" data-book="${e.book}">Book ride</button>`:`<a class="text-link" href="${e.url}" ${e.url.startsWith(official)?'target="_blank" rel="noopener noreferrer"':''}>${e.external?'Official details':'Ride details'}</a>`}${!e.book&&!e.external?'<span class="season-pending">Registration to follow</span>':''}</div>`:''}</li>`;
 function monthCard(month,year,events,annual=false){return `<article class="season-month ${!events.length?'season-rest':''} ${annual&&month<9?'season-earlier':''}"><div class="season-month-heading"><h3>${months[month]}</h3><span>${year}</span></div>${events.length?`<ul>${events.map(event).join('')}</ul>`:'<p class="season-rest-copy">Rest month.</p>'}</article>`;}
 let mode='upcoming';
 function grid(){if(mode==='year')return months.map((m,i)=>monthCard(i,'2026',[...earlier.filter(e=>e.month===i),...current.filter(e=>e.year==='2026'&&e.month===i).map(e=>({...e,current:true}))],true)).join('');let groups=[];for(const e of current){let g=groups.find(g=>g.month===e.month&&g.year===e.year);if(!g){g={month:e.month,year:e.year,events:[]};groups.push(g);}g.events.push({...e,current:true});}return groups.map(g=>monthCard(g.month,g.year,g.events)).join('');}
 const section=()=>`<section class="section season-section" id="ride-calendar" aria-labelledby="season-heading"><div class="season-heading"><h2 id="season-heading">Your riding year.</h2><div class="season-tabs" role="group" aria-label="Calendar view"><button type="button" data-season="upcoming" aria-pressed="true">Upcoming</button><button type="button" data-season="year" aria-pressed="false">Full 2026</button></div></div><div class="season-grid" id="season-grid">${grid()}</div><div class="season-footer"><p id="season-note">Current ride dates. Check each ride for the latest details.</p><a class="text-link" href="${base}/audax-upcoming-rides.ics" download>Save upcoming dates</a></div><p class="season-live" id="season-live" aria-live="polite"></p></section>`;
 function init(){document.querySelectorAll('[data-season]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.season;document.getElementById('season-grid').innerHTML=grid();document.getElementById('season-grid').classList.toggle('season-year',mode==='year');document.querySelectorAll('[data-season]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.season===mode)));document.getElementById('season-note').textContent=mode==='year'?'Earlier dates follow Audax’s season plan; upcoming dates follow current listings.':'Current ride dates. Check each ride for the latest details.';document.getElementById('season-live').textContent=mode==='year'?'Full 2026 calendar shown.':'Upcoming rides from October 2026 to January 2027 shown.';}));}
 return {setRides,section,init};
})();
