// Local-only shop demonstration. No order, payment or personal data is submitted.
const AudaxShop=(()=>{
 const base='/preview/bespoke/audax-malaysia',key='audax-demo-cart-v1';
 const products=[
 {id:'cypress-jersey',name:'Cypress jersey',brand:'Van Rysel',type:'jerseys',photo:'jersey-green',price:249,color:'Cypress green',sizes:['XS','S','M','L','XL'],description:'A clean, close-fitting jersey in deep green. A little colour for the long way round.'},
 {id:'snow-jersey',name:'Snow jersey',brand:'Van Rysel',type:'jerseys',photo:'jersey-white',price:249,color:'Snow white',sizes:['XS','S','M','L','XL'],description:'A crisp white jersey with understated details. Simple kit, open roads.'},
 {id:'ultra-jersey',name:'EDR Ultra jersey',brand:'Van Rysel',type:'jerseys',photo:'jersey-purple',price:289,color:'Lavender',sizes:['XS','S','M','L','XL'],description:'A soft lavender jersey for days spent on the bike. An expressive addition to the collection.'},
 {id:'welt-gravel',name:'Welt gravel',brand:'WELT',type:'bicycles',photo:'bike-blue',price:4890,color:'Blue',sizes:['S','M','L','XL'],description:'Blue frame, tan-wall tyres and a drop-bar silhouette. A gravel bicycle shown as part of the sample collection.'},
 {id:'mmr-x-grip',name:'X-Grip',brand:'MMR',type:'bicycles',photo:'bike-copper',price:7490,color:'Light copper',sizes:['S','M','L','XL'],description:'A copper and black finish with a clean side profile. A sample gravel build for the shop concept.'},
 {id:'polygon-tambora',name:'Tambora G4',brand:'Polygon',type:'bicycles',photo:'bike-sand',price:5290,color:'White',sizes:['S','M','L','XL'],description:'A white gravel bicycle with subtle detailing and tan-wall tyres. Another way to take the long road.'}
 ];
 const money=n=>'RM '+new Intl.NumberFormat('en-MY',{maximumFractionDigits:0}).format(n);
 const photo=(p,extra='')=>`<img src="${base}/assets/${p.photo}-1200.webp" srcset="${base}/assets/${p.photo}-600.webp 600w,${base}/assets/${p.photo}-1200.webp 1200w" sizes="(max-width:760px) 50vw,33vw" alt="${p.brand} ${p.name} in ${p.color}" ${extra}>`;
 const editorial=(name,alt)=>`<img src="${base}/assets/${name}-1200.webp" srcset="${base}/assets/${name}-750.webp 750w,${base}/assets/${name}-1200.webp 1200w,${base}/assets/${name}-2400.webp 2400w" sizes="100vw" alt="${alt}" fetchpriority="high">`;
 let cart=[];try{const stored=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(stored))cart=stored.filter(l=>l&&products.some(p=>p.id===l.id&&p.sizes.includes(l.size))&&Number.isInteger(l.qty)&&l.qty>0&&l.qty<=10).map(l=>({id:l.id,size:l.size,qty:l.qty}));}catch{}
 const total=()=>cart.reduce((n,l)=>n+products.find(p=>p.id===l.id).price*l.qty,0);
 const count=()=>cart.reduce((n,l)=>n+l.qty,0);
 function save(){try{localStorage.setItem(key,JSON.stringify(cart));}catch{}document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count());}
 const notice=()=>`<p class="shop-notice">Sample collection · Demo prices · No orders or payments</p>`;
 const card=p=>`<article class="product-card"><a class="product-photo ${p.type}" href="${base}/shop/${p.id}/">${photo(p,'loading="lazy"')}</a><div class="product-card-info"><p>${p.brand}</p><h3><a href="${base}/shop/${p.id}/">${p.name}</a></h3><span>${money(p.price)}</span></div></article>`;
 const intro=()=>`<section class="section shop-intro"><div><h2>For the<br>long way round.</h2><p>Jerseys and bicycles. Explore the shop concept.</p><a class="button dark" href="${base}/shop/">Explore the shop</a></div><a class="shop-intro-photo" href="${base}/shop/" aria-label="Explore the shop">${editorial('shop-home','A silver bicycle against a dark wall')}</a></section>`;
 const page=()=>`<section class="shop-hero">${editorial('shop-editorial','Two Audax cyclists on a curving hillside road')}<div><h1>Made for<br>more miles.</h1><a class="button" href="#collection">Explore the collection</a></div></section><section class="section shop-collection" id="collection"><div class="shop-heading"><h2>The collection.</h2><button class="button outline" type="button" data-cart>Bag <span data-cart-count>${count()}</span></button></div>${notice()}<div class="shop-toolbar"><div class="shop-filters" role="group" aria-label="Product category">${[['all','All'],['jerseys','Jerseys'],['bicycles','Bicycles']].map(([id,label])=>`<button type="button" data-shop-filter="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div><label class="shop-sort">Sort<select id="shop-sort"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><div class="product-grid" id="product-grid">${products.map(card).join('')}</div><p id="shop-count" class="shop-count" aria-live="polite">6 products</p></section>`;
 const productPage=p=>`<section class="section product-detail"><a class="text-link product-back" href="${base}/shop/">Back to shop</a><div class="product-detail-grid"><div class="product-main-photo ${p.type}">${photo(p,'fetchpriority="high"')}</div><div class="product-buy"><p class="product-brand">${p.brand}</p><h1>${p.name}</h1><p class="product-price">${money(p.price)} <span>Demo price</span></p><p class="product-description">${p.description}</p><p class="product-color">${p.color}</p><form id="product-form" data-product-id="${p.id}"><fieldset><legend>${p.type==='jerseys'?'Jersey size':'Frame size'}</legend><div class="product-sizes">${p.sizes.map(s=>`<label><input type="radio" name="product-size" value="${s}" required><span>${s}</span></label>`).join('')}</div></fieldset><button class="button dark" type="submit">Add to bag</button><p id="product-feedback" role="status"></p></form><p class="shop-demo-note">Sample product and price. Actual stock, sizing and fulfilment are to be confirmed with Audax.</p><details><summary>About this preview</summary><p>Try choosing a size and adding this item to your bag. This shop demonstrates the experience; Audax is not currently selling these products through this preview.</p></details></div></div></section>`;
 const lines=(editable=false)=>cart.map((l,i)=>{const p=products.find(p=>p.id===l.id);return `<article class="bag-line"><div class="bag-thumb">${photo(p,'loading="lazy"')}</div><div class="bag-line-info"><h3>${p.name}</h3><p>${p.color} · ${p.type==='jerseys'?'Size':'Frame'} ${l.size}</p>${editable?`<div class="bag-quantity"><button type="button" data-qty="${i}" data-change="-1" aria-label="Decrease quantity of ${p.name}" ${l.qty===1?'disabled':''}>−</button><span aria-label="Quantity">${l.qty}</span><button type="button" data-qty="${i}" data-change="1" aria-label="Increase quantity of ${p.name}" ${l.qty>=10?'disabled':''}>+</button><button type="button" class="bag-remove" data-remove="${i}" aria-label="Remove ${p.name}, size ${l.size}">Remove</button></div>`:`<p>Quantity ${l.qty}</p>`}</div><strong>${money(p.price*l.qty)}</strong></article>`;}).join('');
 const empty=()=>`<div class="bag-empty"><h3>Your bag is empty.</h3><p>Find something for your next ride.</p><a class="button dark" href="${base}/shop/">Explore the collection</a></div>`;
 const dialog=()=>`<dialog id="cart-dialog" aria-labelledby="cart-title"><div class="bag-head"><h2 id="cart-title">Your bag.</h2><button type="button" id="cart-close" aria-label="Close bag">×</button></div><div id="cart-body"></div></dialog>`;
 const checkout=()=>`<section class="section checkout-page"><h1>Checkout preview.</h1>${notice()}<div id="checkout-body"></div></section>`;
 let opener=null,delivery='collection';
 function renderCart(){const body=document.getElementById('cart-body');if(!body)return;body.innerHTML=cart.length?`${lines(true)}<div class="bag-total"><span>Subtotal</span><strong>${money(total())}</strong></div><p class="shop-demo-note">Demo prices. Sample delivery costs appear in checkout.</p><a class="button dark bag-checkout" href="${base}/shop/checkout/">Preview checkout</a><button type="button" class="bag-continue" data-close-cart>Continue browsing</button>`:empty();}
 function renderCheckout(){const body=document.getElementById('checkout-body');if(!body)return;if(!cart.length){body.innerHTML=empty();return;}const fee=delivery==='collection'?0:cart.some(l=>products.find(p=>p.id===l.id).type==='bicycles')?80:25;body.innerHTML=`<div class="checkout-grid"><div><h2>Your selection.</h2>${lines()}<button class="text-link checkout-edit" type="button" data-cart>Edit bag</button><fieldset class="checkout-fulfilment"><legend>Try a fulfilment option</legend><label><input type="radio" name="demo-fulfilment" value="collection" ${delivery==='collection'?'checked':''}>Collection <span>RM 0 demo fee</span></label><label><input type="radio" name="demo-fulfilment" value="delivery" ${delivery==='delivery'?'checked':''}>Delivery <span>${money(cart.some(l=>products.find(p=>p.id===l.id).type==='bicycles')?80:25)} demo fee</span></label></fieldset></div><aside class="checkout-summary"><h2>Order summary.</h2><dl><div><dt>Products</dt><dd>${money(total())}</dd></div><div><dt>${delivery==='collection'?'Collection':'Delivery'} · demo fee</dt><dd>${money(fee)}</dd></div><div class="checkout-total"><dt>Demo total</dt><dd>${money(total()+fee)}</dd></div></dl><p>No payment or personal details needed. This preview does not place an order.</p><button class="button dark" type="button" id="finish-demo">Finish demo</button><a class="text-link" href="${base}/shop/">Continue shopping</a></aside></div>`;}
 function init(){save();renderCart();renderCheckout();const d=document.getElementById('cart-dialog');
 function close(){d.close();}
 document.getElementById('cart-close').addEventListener('click',close);
 d.addEventListener('close',()=>{document.body.classList.remove('dialog-open');opener?.focus();});
 d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
 document.addEventListener('click',e=>{const t=e.target.closest('[data-cart],[data-close-cart],[data-qty],[data-remove],#finish-demo');if(!t)return;
 if(t.hasAttribute('data-cart')){opener=t;renderCart();d.showModal();document.body.classList.add('dialog-open');}
 if(t.hasAttribute('data-close-cart'))close();
 if(t.hasAttribute('data-qty')||t.hasAttribute('data-remove')){const oldIndex=Number(t.dataset.qty??t.dataset.remove),type=t.hasAttribute('data-remove')?'remove':t.dataset.change==='1'?'increase':'decrease';if(type==='remove')cart.splice(oldIndex,1);else cart[oldIndex].qty=Math.max(1,Math.min(10,cart[oldIndex].qty+Number(t.dataset.change)));save();renderCart();renderCheckout();const controls=d.querySelectorAll(type==='remove'?'[data-remove]':`[data-change="${type==='increase'?'1':'-1'}"]`);const target=controls[Math.min(oldIndex,controls.length-1)];if(target&&!target.disabled)target.focus();else document.getElementById('cart-close').focus();}
 if(t.id==='finish-demo'){const body=document.getElementById('checkout-body');body.innerHTML=`<div class="demo-complete" tabindex="-1"><h2>That’s the experience.</h2><p>Demo complete. No order was placed and no payment was taken.</p><a class="button dark" href="${base}/shop/">Back to the collection</a></div>`;body.firstElementChild.focus();}
 });
 document.addEventListener('change',e=>{if(e.target.name==='demo-fulfilment'){delivery=e.target.value;renderCheckout();document.querySelector(`input[name="demo-fulfilment"][value="${delivery}"]`).focus();}});
 const form=document.getElementById('product-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const p=products.find(p=>p.id===form.dataset.productId),size=new FormData(form).get('product-size');if(!p.sizes.includes(size))return;let l=cart.find(l=>l.id===p.id&&l.size===size);if(l&&l.qty>=10){document.getElementById('product-feedback').textContent='The demo bag is limited to 10 of each size.';return;}if(l)l.qty++;else cart.push({id:p.id,size,qty:1});save();renderCart();document.getElementById('product-feedback').innerHTML=`Added to your bag. <button type="button" class="text-link" data-cart>View bag</button>`;});
 let filter='all';const sort=document.getElementById('shop-sort');function filterGrid(){let list=products.filter(p=>filter==='all'||p.type===filter);if(sort.value!=='featured')list=list.slice().sort((a,b)=>sort.value==='low'?a.price-b.price:b.price-a.price);document.getElementById('product-grid').innerHTML=list.map(card).join('');document.getElementById('shop-count').textContent=list.length+' products';document.querySelectorAll('[data-shop-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shopFilter===filter)));}
 if(sort){document.querySelectorAll('[data-shop-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.shopFilter;filterGrid();}));sort.addEventListener('change',filterGrid);}
 }
 return {products,page,productPage,checkout,dialog,intro,init};
})();
